development:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxx
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>

test:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxx

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>